"""Base Skill interface for Phase 3: Governance & Advanced Skills."""

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class SkillCategory(str, Enum):
    """Categories of skills."""

    DEVOPS = "devops"
    CODE = "code"
    SECURITY = "security"
    FINOPS = "finops"
    CAPACITY = "capacity"
    MONITORING = "monitoring"
    INCIDENT = "incident"
    RELIABILITY = "reliability"
    COMPLIANCE = "compliance"
    OBSERVABILITY = "observability"  # Phase 5: Observability skills
    PERFORMANCE = "performance"      # Phase 5: Performance skills


class SkillPriority(str, Enum):
    """Priority levels for skills."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class SkillStatus(str, Enum):
    """Status of skill execution."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class AnalysisResult(BaseModel):
    """Result of a skill analysis."""

    success: bool = Field(..., description="Whether analysis succeeded")
    skill_id: str = Field(..., description="ID of the skill that generated this")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="Confidence score")
    data: dict[str, Any] = Field(default_factory=dict, description="Analysis data")
    errors: list[str] = Field(default_factory=list, description="Error messages")
    warnings: list[str] = Field(default_factory=list, description="Warning messages")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class Recommendation(BaseModel):
    """A recommendation generated by a skill."""

    title: str = Field(..., description="Title of the recommendation")
    description: str = Field(..., description="Detailed description")
    priority: SkillPriority = Field(default=SkillPriority.MEDIUM)
    action_type: str = Field(default="manual", description="Type of action: manual, automated, hybrid")
    estimated_effort: str | None = Field(None, description="Estimated effort to implement")
    risk_level: str = Field(default="low", description="Risk level: low, medium, high, critical")
    commands: list[str] = Field(default_factory=list, description="Suggested commands")
    references: list[str] = Field(default_factory=list, description="Reference links")


class SkillConfig(BaseModel):
    """Configuration for a skill."""

    enabled: bool = Field(default=True)
    priority: SkillPriority = Field(default=SkillPriority.MEDIUM)
    timeout_seconds: int = Field(default=300, ge=1, le=3600)
    max_retries: int = Field(default=3, ge=0, le=10)
    parameters: dict[str, Any] = Field(default_factory=dict)
    schedule: str | None = Field(None, description="Cron schedule for recurring execution")


class BaseSkill(ABC):
    """Base class for all skills.

    All skills must inherit from this class and implement the required methods.
    """

    # Class attributes - must be defined by subclasses
    skill_id: str
    name: str
    description: str
    category: SkillCategory
    priority: SkillPriority
    version: str = "1.0.0"
    # False = no real data-source integration yet (mock/empty output).
    # Set via SkillRegistry.STUB_SKILLS; subclasses may also declare it directly.
    implemented: bool = True

    def __init__(self, config: SkillConfig | None = None):
        """Initialize the skill with optional configuration.

        Args:
            config: Optional skill configuration
        """
        self.config = config or SkillConfig()
        self._validate_config()

    @abstractmethod
    async def analyze(
        self,
        project: str,
        parameters: dict[str, Any],
        context: dict[str, Any] | None = None,
    ) -> AnalysisResult:
        """Run the skill analysis.

        Args:
            project: Project/service name to analyze
            parameters: Skill-specific parameters
            context: Additional context (e.g., from registry)

        Returns:
            AnalysisResult containing findings
        """

    @abstractmethod
    async def get_recommendations(
        self,
        analysis_id: str,
        project: str,
    ) -> list[Recommendation]:
        """Get recommendations based on analysis results.

        Args:
            analysis_id: ID of previous analysis result
            project: Project/service name

        Returns:
            List of recommendations
        """

    def get_metadata(self) -> dict[str, Any]:
        """Get skill metadata.

        Returns:
            Dictionary with skill metadata
        """
        return {
            "skill_id": self.skill_id,
            "name": self.name,
            "description": self.description,
            "category": self.category,
            "priority": self.priority,
            "version": self.version,
            "enabled": self.config.enabled,
            "implemented": self.implemented,
        }

    def validate_parameters(self, parameters: dict[str, Any]) -> tuple[bool, list[str]]:
        """Validate skill parameters.

        Args:
            parameters: Parameters to validate

        Returns:
            Tuple of (is_valid, error_messages)
        """
        # Base implementation - subclasses should override
        return True, []

    def _validate_config(self) -> None:
        """Validate skill configuration.

        Raises:
            ValueError: If configuration is invalid
        """
        if self.config.timeout_seconds < 1:
            raise ValueError("timeout_seconds must be at least 1")
        if self.config.max_retries < 0:
            raise ValueError("max_retries cannot be negative")

    async def _execute_with_retry(
        self,
        func,
        *args,
        **kwargs,
    ) -> Any:
        """Execute function with retry logic.

        Args:
            func: Function to execute
            *args: Function arguments
            **kwargs: Function keyword arguments

        Returns:
            Function result

        Raises:
            Exception: If all retries fail
        """
        import asyncio

        last_error = None
        for attempt in range(self.config.max_retries + 1):
            try:
                return await func(*args, **kwargs)
            except Exception as e:
                last_error = e
                if attempt < self.config.max_retries:
                    wait_time = 2 ** attempt  # Exponential backoff
                    await asyncio.sleep(wait_time)
                else:
                    raise last_error from e

    def _log(self, level: str, message: str, **kwargs) -> None:
        """Log a message with skill context.

        Args:
            level: Log level (info, warning, error)
            message: Log message
            **kwargs: Additional context
        """
        import logging

        logger = logging.getLogger(__name__)
        log_message = f"[{self.skill_id}] {message}"
        getattr(logger, level.lower())(log_message, extra={"skill": self.skill_id, **kwargs})


class SkillExecutionError(Exception):
    """Exception raised when skill execution fails."""

    def __init__(
        self,
        skill_id: str,
        message: str,
        details: dict[str, Any] | None = None,
    ):
        """Initialize the exception.

        Args:
            skill_id: ID of the skill that failed
            message: Error message
            details: Additional error details
        """
        self.skill_id = skill_id
        self.details = details or {}
        super().__init__(f"[{skill_id}] {message}")


class SkillTimeoutError(SkillExecutionError):
    """Exception raised when skill execution times out."""



class SkillValidationError(Exception):
    """Exception raised when skill parameters are invalid."""

    def __init__(
        self,
        skill_id: str,
        parameter: str,
        message: str,
    ):
        """Initialize the exception.

        Args:
            skill_id: ID of the skill
            parameter: Invalid parameter name
            message: Validation error message
        """
        self.skill_id = skill_id
        self.parameter = parameter
        self.message = f"Invalid parameter '{parameter}': {message}"
        super().__init__(self.message)

    def __str__(self) -> str:
        """Return formatted error message."""
        return f"[{self.skill_id}] {self.message}"
